export const GET_LAST_SEEN = "GET_LAST_SEEN";
export const ADD_LAST_SEEN = "ADD_LAST_SEEN";
export const SAVE_SEARCH_HISTORY = "SAVE_SEARCH_HISTORY ";
export const REMOVE_ALL_SEARCH_HISTORY = "REMOVE_ALL_SEARCH_HISTORY  ";
export const REMOVE_SINGLE_SEARCH_HISTORY = "REMOVE_SINGLE_SEARCH_HISTORY  ";
