export const AUTH_PROCESS = "AUTH_PROCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_PROCESS = "LOGOUT_PROCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
