export const GET_ALL_PRODUCT_PROCESS = "GET_ALL_PRODUCT_PROCESS";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL";

export const GET_PRODUCT_DISCOUNT_PROCESS = "GET_PRODUCT_DISCOUNT_PROCESS";
export const GET_PRODUCT_DISCOUNT_SUCCESS = "GET_PRODUCT_DISCOUNT_SUCCESS";
export const GET_PRODUCT_DISCOUNT_FAIL = "GET_PRODUCT_DISCOUNT_FAIL";

export const GET_PRODUCT_DETAIL_PROCESS = "GET_PRODUCT_DETAIL_PROCESS";
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_PRODUCT_DETAIL_FAIL = "GET_PRODUCT_DETAIL_FAIL";

export const GET_ALL_CATEGORY_PROCESS = "GET_ALL_CATEGORY_PROCESS";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAIL = "GET_ALL_CATEGORY_FAIL";

export const SEARCH_PRODUCT_PROCESS = "SEARCH_PRODUCT_PROCESS";
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_FAIL = "SEARCH_PRODUCT_FAIL";

export const SEARCH_RESULT_PROCESS = "SEARCH_RESULT_PROCESS";
export const SEARCH_RESULT_SUCCESS = "SEARCH_RESULT_SUCCESS";
export const SEARCH_RESULT_FAIL = "SEARCH_RESULT_FAIL";
